# Generated by Django 5.0 on 2025-12-27 06:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_solver", "0015_remove_usersubscription_auto_pay_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[("basic", "BASIC"), ("premium", "PREMIUM")],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="plan",
            field=models.CharField(
                choices=[("basic", "BASIC"), ("premium", "PREMIUM")],
                default="basic",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Promo code (e.g., WELCOME100)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                            ("free_trial", "Free Trial"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0-100) or Fixed Amount",
                        max_digits=10,
                    ),
                ),
                (
                    "applicable_plans",
                    models.JSONField(
                        default=list,
                        help_text="List of plan names (e.g., ['scholar', 'genius'])",
                    ),
                ),
                (
                    "max_uses",
                    models.IntegerField(
                        blank=True,
                        help_text="Max total uses (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "max_uses_per_user",
                    models.IntegerField(default=1, help_text="Max uses per user"),
                ),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("times_used", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["code"], name="question_so_code_21e094_idx"),
                    models.Index(
                        fields=["is_active", "valid_from", "valid_until"],
                        name="question_so_is_acti_dde1f5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PromoCodeUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "discounted_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "discount_applied",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promo_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="question_solver.promocode",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="question_solver.usersubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-used_at"],
                "indexes": [
                    models.Index(
                        fields=["promo_code", "user_id"],
                        name="question_so_promo_c_3e3b86_idx",
                    ),
                    models.Index(
                        fields=["user_id", "-used_at"],
                        name="question_so_user_id_b1df04_idx",
                    ),
                ],
            },
        ),
    ]
